/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false --strict-vars false` (hash: 8a4865e91536df10ad9e3f53bbdc2284)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		LOADER: WorkerLoader;
		GlobalOutbound: Service<typeof import("./src/index").GlobalOutbound>;
		ExposeSomeFunctions: Service<typeof import("./src/index").ExposeSomeFunctions>;
	}
}
interface Env extends Cloudflare.Env {}
