/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false --strict-vars false` (hash: 052d51180a5efa58a6f0a7107c4a3772)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "User";
	}
	interface Env {
		KV: KVNamespace;
		User: DurableObjectNamespace /* User */;
		globalOutbound: Service<typeof import("./src/index").globalOutbound>;
		ExposeSomeFunctions: Service<typeof import("./src/index").ExposeSomeFunctions>;
		LOADER: any;
	}
}
interface Env extends Cloudflare.Env {}
