/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false --strict-vars false` (hash: 29794ed8965ccec82e11c60f22d0b2fb)
declare namespace Cloudflare {
	interface Env {
		KV: KVNamespace;
		User: DurableObjectNamespace /* User */;
		globalOutbound: Service<typeof import("./src/index").globalOutbound>;
		GreeterLoopback: Service<typeof import("./src/index").GreeterLoopback>;
		LOADER: any;
	}
}
interface Env extends Cloudflare.Env {}
